# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3309c9b6b6092d611826e81a0b72a423690a01f54022d45256089aba0211319ccbac21a7ba6705b914cd397c74ff591e447e9a436ed47b66b34fa2ef07aa0b9

test:
  secret_key_base: 28ae0a966b216f30fbc025f5dc60fd505f346f12385c781910d6393b3543da959aeff993da7f97763e42cd1692fbcf766f3c878fe28dc9cfc35019e7b190294c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
